version: '3'

services:
  influxdb:
    image: docker.io/library/influxdb:2.7.1
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUX_DB=crypto
      - INFLUX_ADMIN_USER=admin
      - INFLUX_ADMIN_PASSWORD=admin123456